# Programming exercise 8: The AKLT model and matrix product states

Due on Monday, 24.12.2018, 23.59h

### Total: 100 points

In [3]:
# load standard libraries

import scipy.sparse as sparse
import scipy.sparse.linalg as sLA
import numpy as np
import numpy.linalg as npla
import matplotlib.pyplot as plt

### Exercise 1: Solving the AKLT model with exact diagonalization (25 points)

This time we want to study a quantum many-body model for spins known as the AKLT model which was introduced in the 80's to explore the Haldane conjecture(see https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.59.799). It has a couple of remarkable features that will allow us to use it as playground for testing the basic ideas surrounding matrix product states. As additional practice on how to build general spin models and exact diagonalization, we will start by solving it here by numerical means and then compare the result to some theoretical predictions. You can use some of the code from the last exercise as a basis but make sure to modify the operators as now we are working with spin 1!  

As mentioned, this is a spin 1 model and it lives in a one dimensional chain with periodic boundary conditions (using the correct boundary condition is critical here) and the Hamiltonian is given by:

$$
H=-J\sum_{i=0}^{N-1}\left(\frac{1}{3} +\frac{1}{2}S^{(i)}\cdot S^{(i+1)}+\frac{1}{6}(S^{(i)}\cdot S^{(i+1)})^2\right)
$$
Remenber that, due to the periodic boundary conditions, the Nth spin is identified with 0th spin. $S^{(i)}$ denotes the vector of spin sperators $(S_x^{(i)}, S_y^{(i)}, S_z^{(i)})$. It might be convenient to use the following representation for the spin their products:
$$
S^{(i)}\cdot S^{(i+1)} = S_z^{(i)} S_z^{(i+1)}+\frac{1}{2}\left(S_+^{(i)}S_-^{(i+1)}+S_-^{(i)}S_+^{(i+1)}\right)
$$
where the relevant spin 1 spin operators are $S_z=-|-1\rangle\langle-1| + |+1\rangle\langle+1|$, $S_+=|+1\rangle\langle 0| + |0\rangle\langle -1|$ and $S_- = S_+^\dagger$ (with $|s\rangle$ denoting the basis states in the $S_z$ eigenbasis).

Build the Hamiltonian in the standard product basis ($J$ is just a global energy scale and can be set to 1).

First you can test your implementation by calculating the ground state energy and making sure it is zero as this is the theoretical prediction. Another test is the magnetization on the z direction which should also be zero.

Once you are confident that your code is working you should compute the energy gap between ground and first excited state for a couple of system sizes $N$ and see how it behaves. Is the system gapped? This question is directly related to the Haldane conjecture.

Finally, compute the correlation function $\langle S_z^{(i)}S_z^{(i+r)} \rangle$ as a function of $r$ and compare to the theoretical result:
$$
\langle S_z^{(i)}S_z^{(i+r)}\rangle \propto \left(\frac{-1}{3}\right)^r
$$

It probably won't look so good as the exact diagonalization is not the best tool to study this but you should get some agreement.


Optional: Investigate what happend for open boundary conditions and see if there is any qualitative difference.

In [4]:
plus=np.array([1,0,0])
null=np.array([0,1,0])
minus=np.array([0,0,1])
sz=-np.outer(minus,minus)+np.outer(plus,plus)
sp=np.sqrt(2)*(np.outer(plus,null)+np.outer(null,minus))
sm=np.transpose(sp)

In [5]:
# spin operators
# sparse spin operators
szSp = sparse.csr_matrix(sz)
spSp = sparse.csr_matrix(sp)
smSp = sparse.csr_matrix(sm)
oneSp = sparse.identity(3)
# function that builds all single spin operators
def BuildSingleSpinOps(N):
    szi=[]
    spi=[]
    smi=[]
    # build the single spin operators
    for i in range(N):
        szi.append( sparse.kron(sparse.kron(sparse.identity(3**(N-i-1)),szSp),sparse.identity(3**i)) )
        spi.append( sparse.kron(sparse.kron(sparse.identity(3**(N-i-1)),spSp),sparse.identity(3**i)) )
        smi.append( sparse.kron(sparse.kron(sparse.identity(3**(N-i-1)),smSp),sparse.identity(3**i)) )
        
    return szi, spi, smi

# Build the transverse field ising Hamiltonian with periodic boundaries
def Build_H_TFIM(N):
    Hmat = N/3*sparse.identity(3**N)
    for i in range(N):
        product=Szis[i]@Szis[(i+1)%N] +1/2*(Spis[i]@Smis[(i+1)%N]+Smis[i]@Spis[(i+1)%N])
        Hmat = Hmat +1/2*(product)+1/6*product@product
    return Hmat



In [6]:
print(sz)
print(sp)
print(sm)
print(smSp,smSp.toarray())#,spSp)

[[ 1  0  0]
 [ 0  0  0]
 [ 0  0 -1]]
[[0.         1.41421356 0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
[[0.         0.         0.        ]
 [1.41421356 0.         0.        ]
 [0.         1.41421356 0.        ]]
  (1, 0)	1.4142135623730951
  (2, 1)	1.4142135623730951 [[0.         0.         0.        ]
 [1.41421356 0.         0.        ]
 [0.         1.41421356 0.        ]]


In [7]:
N = 10
dim = 3**N

Szis, Spis, Smis = BuildSingleSpinOps(N)
# print(sxis[0].toarray())
# print(syis[0].toarray())
# print(szis[0].toarray())
    
# calculate the ground state and compare to analytical result
Hmat = Build_H_TFIM(N)
sLA.eigsh(Hmat,k=3,which='SA')



(array([-1.15379235e-15,  3.50091873e-01,  3.50091873e-01]),
 array([[-2.81320845e-17,  6.61484040e-18, -1.73747451e-18],
        [ 2.41154592e-17, -7.27207069e-18,  1.13244521e-17],
        [-4.96954530e-18, -8.50723840e-19,  2.82852166e-18],
        ...,
        [ 3.11415790e-18, -3.59162564e-19,  3.50194040e-18],
        [ 2.89855616e-17, -5.87253553e-18,  8.06286014e-19],
        [-4.72729269e-17,  9.14684278e-18, -3.87567958e-18]]))

In [8]:
ground=[]
first=[]
dif=[]
Ns=np.linspace(5,20,1)
for N in Ns:
    dim=3**N
    Szis, Spis, Smis = BuildSingleSpinOps(N)
    Hmat=Build_H_TFIM(N)
    eigval,eigvec=slA.eigsh(Hmat,k=3,which="SA")
    ground.append(eigval[0])
    first.append(eigval[1])
    dif.append(eigval[1]-eigval[0])
plt.plot(Ns,dif)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [ ]:
for i in range(len(Bvec)):
    Hmat = Build_H_TFIM(N,Bvec[i])
    result[i,:3], evecs = sLA.eigsh(Hmat,k=3,which='SA') # numerical ground state energy
    result[i,3] = -np.sum(sqrt(1+Bvec[i]**2-2*Bvec[i]*cos(2*pi/N*np.arange(-(N-1)/2,(N-1)/2+1,1)))) # analytical ground state energy

plt.plot(Bvec,result[:,0]/N)
plt.plot(Bvec,result[:,3]/N,'+')
plt.legend(['numerical diagonalization','analytical'])
plt.xlabel('transverse field B/J')
plt.ylabel('ground state energy density $E_0/N$')
plt.show()

plt.plot(Bvec,result[:,1]-result[:,0])
plt.plot(Bvec,result[:,2]-result[:,0])
plt.legend(['$E_1-E_0$','$E_2-E_0$'])
plt.xlabel('transverse field B/J')
plt.ylabel('gap')
plt.show()

### Exercise 2: Entanglement in the phase diagram (25 points)

Now we are going to look at entanglement in the AKLT model but to make things more interesting we add a paramenter $\theta$ to the Hamiltonian:
$$
H=-J\sum_{i=0}^{N-1}\left(\frac{cos(\theta)}{3 cos(\theta_{0})} +\frac{cos(\theta)}{2 cos(\theta_{0})}S^{(i)}\cdot S^{(i+1)}+\frac{sin(\theta)}{6 cos(\theta_{0})}(S^{(i)}\cdot S^{(i+1)})^2\right)
$$
where $\theta_0 = \text{arctan}(1/3)$ is a special angle that allow us to go back to the original Hamiltonian with $\theta=\theta_0$.


Study what happens to the gap of the system as you change $\theta$, moving away from $\theta_0$, and interpret your results. After this you should look at the entanglement of the ground state for different $\theta$ taking into account your conclusions about the gap. What happens to the entanglement entropy and the schmidt rank as $\theta$ changes?

Tip: a nice trick to compute partial traces is to use the function reshape() as it allows you to rewrite your state as a matrix in the way required for a Schmidt decomposition. After that all you need to do to get the entanglement spectrum is perform a svd (also available in the usual places) and look at the singular values.

### Exercise 3: MPS description (50 points)

Finally we will use the MPS machinery and explain why we chose to study the AKLT model (besides the fact that it is a pretty cool model :)). Usually for any given Hamiltonian it is necessary to apply a (complicated) procedure to find a good MPS aproximation for the ground states but the AKLT ground states is special in that it admits an exact MPS description so we can directly apply the tensor network techniques to it! The representation only requires bond dimension 2 and is given by the following 2x2 matrices:
$$
A_{+1}=\sqrt{\frac{2}{3}} \sigma_+\\
A_{0}=-\sqrt{\frac{1}{3}} \sigma_z\\
A_{-1}=-\sqrt{\frac{2}{3}} \sigma_-\\
$$

Show that this really gives the ground state by comparing it to the states you got from exact diagonalization. To do so you should use the expression for MPS ansatz to reconstruct the corresponding state in your basis
$$
|\psi_{\text{mps}}\rangle = \sum_{s_i} Tr(A_{s_0}A_{s_1}\dots A_{s_{N-1}})|s_0 s_1 \dots s_{N-1}\rangle
$$
and compute the overlap $\langle\psi_{\text{ed}}|\psi_{\text{mps}}\rangle$ with the exact diagonalzation ground state. Of course, this is not very smart as we are using our efficiennt MPS representation to reconstruct the inefficient ED representation, but it is a good sanity check nonetheless. 

You might notice a small deviation on the overlap. This comes from the fact that the MPS state is not normalized and you can see this by computing the norm directly from the matrices:
$$
\langle\psi_{\text{mps}}|\psi_{\text{mps}}\rangle = Tr(E^n)
$$
where
$$
E = \sum_s A_s\otimes A_s^*\\
$$
is the local matrix corresponding to the identity operator. To speed up this calculation you can diagonalize E so that you only need to compute powers of the eigenvales and not the actual matrix. Show that the deviation from 1 is small and vanishes exponentially for large systems.

Now, for the real benefits of the MPS, let's compute the correlation function $\langle S_z^{(i)}S_z^{(i+r)}\rangle$ from exercise 1. This can be done for very large systems by simply replacing two E matrices in the expression for the norm with
$$
E_z = \sum_{s,s'}\langle s|S_z|s'\rangle A_s\otimes A_{s'}^*
$$
which is the local matrix for $S_z$. Think about the correct position where the $E_z$ should go and use this to compute the correlation function. Compare the results to the theoretical prediction mentioned in the first exercise.

Optional: The AKLT model has a hidden order that manifests it self through a string operator:
$$
\langle S_z^{(i)}\,\exp\left[\sum_{i<k<j}i \pi S_z^{(k)}\right] \,  S_z^{(j)}\rangle
$$
Compute this order parameter and show that it maintains a constant value for $|i-j|>2$